version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Running npm install...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build-all
  post_build:
    commands:
      - echo Build finished on `date`
      - echo Deployment started on `date`

artifacts:
  files:
    - styleguide/**/*